"""Tests for Étape A: data pipeline — Elo engine, style extractor, form engine, backtest."""
from __future__ import annotations

import math
import sys
from pathlib import Path

import pandas as pd
import pytest

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

DATA_DIR = ROOT / "data"
ELO_SNAPSHOT = DATA_DIR / "elo_snapshot.csv"
STYLE_METRICS = DATA_DIR / "style_metrics.csv"
TEAMS_CSV = DATA_DIR / "teams.csv"


# =============================================================================
# ELO ENGINE
# =============================================================================

def test_elo_engine_loads_all_48():
    from wc2026.data_pipeline.elo_engine import fetch_elo_data
    records = fetch_elo_data(cache_path=DATA_DIR / "elo_raw_cache.tsv")
    assert len(records) == 48, f"Expected 48 teams, got {len(records)}"


def test_elo_engine_sco_is_scotland_not_seychelles():
    """Critical: SCO must map to 'SQ' (Scotland ≈1782) not 'SC' (Seychelles ≈853)."""
    from wc2026.data_pipeline.elo_engine import fetch_elo_data
    records = fetch_elo_data(cache_path=DATA_DIR / "elo_raw_cache.tsv")
    assert "SCO" in records, "SCO missing from records"
    r = records["SCO"]
    assert r.elo_current > 1700, f"SCO elo={r.elo_current} looks like Seychelles (<1700), check FIFA3_TO_ELO2 mapping"
    assert r.elo2 == "SQ", f"SCO should map to SQ (Scotland), got {r.elo2!r}"


def test_elo_engine_top_teams_have_high_elo():
    from wc2026.data_pipeline.elo_engine import fetch_elo_data
    records = fetch_elo_data(cache_path=DATA_DIR / "elo_raw_cache.tsv")
    for code, min_elo in [("ESP", 2000), ("FRA", 2000), ("ARG", 2000), ("BRA", 1900)]:
        if code in records:
            assert records[code].elo_current >= min_elo, \
                f"{code} elo={records[code].elo_current} < {min_elo}"


def test_elo_engine_qat_low_elo():
    """Qatar underperformed at WC 2022 host — should have low Elo."""
    from wc2026.data_pipeline.elo_engine import fetch_elo_data
    records = fetch_elo_data(cache_path=DATA_DIR / "elo_raw_cache.tsv")
    assert records["QAT"].elo_current < 1500


def test_elo_wc2022_approx_plausible():
    """WC2022 Elo approximation should be within ±300 of current Elo."""
    from wc2026.data_pipeline.elo_engine import fetch_elo_data
    records = fetch_elo_data(cache_path=DATA_DIR / "elo_raw_cache.tsv")
    for code, rec in records.items():
        diff = abs(rec.elo_wc2022_approx - rec.elo_current)
        assert diff < 500, f"{code}: wc2022_approx={rec.elo_wc2022_approx} vs current={rec.elo_current} (diff={diff})"


def test_elo_to_form_range():
    from wc2026.data_pipeline.elo_engine import elo_to_form
    for elo in [1400, 1600, 1800, 2000, 2200]:
        for d1yr in [-300, -100, 0, 100, 300]:
            score = elo_to_form(elo, d1yr)
            assert 0.0 <= score <= 100.0, f"elo_to_form({elo}, {d1yr}) = {score} out of [0,100]"


def test_elo_to_form_monotone_in_elo():
    """Higher Elo → higher (or equal) form, holding d1yr constant."""
    from wc2026.data_pipeline.elo_engine import elo_to_form
    scores = [elo_to_form(elo, 0) for elo in [1500, 1700, 1900, 2100]]
    for i in range(len(scores) - 1):
        assert scores[i] <= scores[i + 1], "form should not decrease with higher Elo"


def test_elo_to_form_monotone_in_momentum():
    """Higher d1yr (more momentum) → higher form, holding elo constant."""
    from wc2026.data_pipeline.elo_engine import elo_to_form
    scores = [elo_to_form(1900, d) for d in [-200, -100, 0, 100, 200]]
    for i in range(len(scores) - 1):
        assert scores[i] <= scores[i + 1], "form should not decrease with higher momentum"


# =============================================================================
# ELO SNAPSHOT CSV (generated by pipeline)
# =============================================================================

@pytest.mark.skipif(not ELO_SNAPSHOT.exists(), reason="elo_snapshot.csv not yet generated")
def test_elo_snapshot_has_48_rows():
    df = pd.read_csv(ELO_SNAPSHOT)
    assert len(df) == 48, f"Expected 48 rows, got {len(df)}"


@pytest.mark.skipif(not ELO_SNAPSHOT.exists(), reason="elo_snapshot.csv not yet generated")
def test_elo_snapshot_required_columns():
    df = pd.read_csv(ELO_SNAPSHOT)
    for col in ["code", "elo_current", "d_1yr", "d_2yr", "elo_wc2022", "elo_form_score"]:
        assert col in df.columns, f"Missing column {col!r}"


@pytest.mark.skipif(not ELO_SNAPSHOT.exists(), reason="elo_snapshot.csv not yet generated")
def test_elo_snapshot_form_scores_valid_range():
    df = pd.read_csv(ELO_SNAPSHOT)
    assert (df["elo_form_score"] >= 0).all()
    assert (df["elo_form_score"] <= 100).all()


# =============================================================================
# STYLE METRICS CSV
# =============================================================================

@pytest.mark.skipif(not STYLE_METRICS.exists(), reason="style_metrics.csv not yet generated")
def test_style_metrics_ppda_plausible():
    """PPDA should be positive; typical range 5-20."""
    df = pd.read_csv(STYLE_METRICS)
    assert (df["ppda"] > 0).all(), "PPDA must be positive"
    assert (df["ppda"] < 100).all(), "PPDA > 100 indicates a bug"


@pytest.mark.skipif(not STYLE_METRICS.exists(), reason="style_metrics.csv not yet generated")
def test_style_metrics_shot_quality_range():
    df = pd.read_csv(STYLE_METRICS)
    assert (df["shot_quality"] >= 0).all()
    assert (df["shot_quality"] <= 1).all(), "shot_quality (mean xG) should be < 1"


@pytest.mark.skipif(not STYLE_METRICS.exists(), reason="style_metrics.csv not yet generated")
def test_style_metrics_rates_are_fractions():
    df = pd.read_csv(STYLE_METRICS)
    for col in ["comeback_rate", "choke_rate", "press_intensity"]:
        if col in df.columns:
            assert (df[col] >= 0).all(), f"{col} has negative values"
            assert (df[col] <= 1).all(), f"{col} > 1"


# =============================================================================
# TEAMS CSV (after pipeline update)
# =============================================================================

@pytest.mark.skipif(not TEAMS_CSV.exists(), reason="teams.csv missing")
def test_teams_csv_has_new_elo_columns():
    df = pd.read_csv(TEAMS_CSV)
    for col in ["elo_current", "d_1yr", "d_2yr", "form_data_driven"]:
        assert col in df.columns, f"Column {col!r} not added by pipeline"


@pytest.mark.skipif(not TEAMS_CSV.exists(), reason="teams.csv missing")
def test_teams_csv_form_valid_range():
    df = pd.read_csv(TEAMS_CSV)
    assert (df["form"] >= 0).all(), "form has negative values"
    assert (df["form"] <= 100).all(), "form exceeds 100"


@pytest.mark.skipif(not TEAMS_CSV.exists(), reason="teams.csv missing")
def test_teams_csv_esp_has_highest_elo():
    """Spain has highest Elo (2155) among WC 2026 teams."""
    df = pd.read_csv(TEAMS_CSV)
    if "elo_current" in df.columns:
        max_code = df.loc[df["elo_current"].idxmax(), "code"]
        assert max_code == "ESP", f"Expected ESP as max Elo, got {max_code}"


# =============================================================================
# FORM ENGINE
# =============================================================================

def test_form_engine_compute_final_form():
    from wc2026.data_pipeline.form_engine import _compute_final_form
    # High Elo, positive momentum, good style → near 100
    high = _compute_final_form(2150, 150, 0.15, 0.9)
    assert high > 70, f"High form expected >70, got {high}"

    # Low Elo, negative momentum, poor style → near 0
    low = _compute_final_form(1420, -200, 0.05, 0.1)
    assert low < 30, f"Low form expected <30, got {low}"

    # Result must always be in [0, 100]
    for elo in [1400, 1600, 1800, 2000, 2200]:
        for d in [-300, 0, 300]:
            f = _compute_final_form(elo, d, 0.10, 0.5)
            assert 0 <= f <= 100, f"_compute_final_form({elo},{d}) = {f} out of [0,100]"


def test_form_engine_none_style_uses_defaults():
    """With no style data, form should still compute (uses Elo only)."""
    from wc2026.data_pipeline.form_engine import _compute_final_form
    f1 = _compute_final_form(1900, 50, None, None)
    f2 = _compute_final_form(1900, 50, 0.10, 0.5)
    # Should give same result (None defaults are 0.10 and 0.5)
    assert abs(f1 - f2) < 0.1, f"None style gave {f1}, explicit defaults gave {f2}"


# =============================================================================
# BRIER SCORE MATH
# =============================================================================

def test_brier_score_random_baseline():
    """Random model (uniform probabilities) Brier should equal analytical baseline."""
    from wc2026.data_pipeline.backtest import _brier_score, WC2022_ALL_TEAMS, WC2022_GROUP_SURVIVORS

    n = len(WC2022_ALL_TEAMS)  # 32
    n_pos = len(WC2022_GROUP_SURVIVORS)  # 16
    p = n_pos / n  # 0.5 for group survival
    probs_uniform = {t: p for t in WC2022_ALL_TEAMS}

    brier = _brier_score(probs_uniform, WC2022_GROUP_SURVIVORS, WC2022_ALL_TEAMS)
    # Analytical: n_pos * (p-1)² + n_neg * p² / n = p*(1-p) = 0.25 for p=0.5
    expected = p * (1 - p)
    assert abs(brier - expected) < 1e-6, f"Brier uniform={brier:.6f}, expected={expected:.6f}"


def test_brier_score_perfect_model():
    """A model assigning 100% to each correct team gets Brier = 0."""
    from wc2026.data_pipeline.backtest import _brier_score, WC2022_ALL_TEAMS, WC2022_GROUP_SURVIVORS

    perfect_probs = {
        t: (1.0 if t in WC2022_GROUP_SURVIVORS else 0.0)
        for t in WC2022_ALL_TEAMS
    }
    brier = _brier_score(perfect_probs, WC2022_GROUP_SURVIVORS, WC2022_ALL_TEAMS)
    assert brier == 0.0, f"Perfect model Brier should be 0, got {brier}"


def test_brier_score_group_survival_beats_random():
    """Our backtest result should beat the random baseline on group survival."""
    backtest_csv = ROOT / "outputs" / "backtest_wc2022.csv"
    if not backtest_csv.exists():
        pytest.skip("backtest_wc2022.csv not generated yet")

    from wc2026.data_pipeline.backtest import (
        _brier_score, WC2022_ALL_TEAMS, WC2022_GROUP_SURVIVORS,
    )
    df = pd.read_csv(backtest_csv)
    probs = dict(zip(df["team"], df["prob_group_survival"]))
    brier = _brier_score(probs, WC2022_GROUP_SURVIVORS, WC2022_ALL_TEAMS)

    random_baseline = 0.25  # p=0.5 group survival → Brier = 0.25
    assert brier < random_baseline, \
        f"Model Brier={brier:.4f} should beat random={random_baseline}"


def test_brier_score_champion_sets_sensible():
    """WC2022_CHAMPION should have exactly 1 team (ARG)."""
    from wc2026.data_pipeline.backtest import WC2022_CHAMPION, WC2022_ALL_TEAMS
    assert len(WC2022_CHAMPION) == 1
    assert "ARG" in WC2022_CHAMPION
    assert len(WC2022_ALL_TEAMS) == 32
